<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Messages[<!ELEMENT Messages (Package*)>

<!ELEMENT Package (Error*)>
<!ATTLIST Package ID CDATA #REQUIRED>
<!ATTLIST Package DefaultComponent CDATA #REQUIRED>

<!ELEMENT Error (#PCDATA)>
<!ATTLIST Error Key CDATA #REQUIRED>
<!ATTLIST Error _locID CDATA "0">
<!ATTLIST Error Component CDATA #IMPLIED>
<!ATTLIST Error NativeErrorCode CDATA #REQUIRED>
<!ATTLIST Error Params CDATA "0">]>

<Messages>
    <!-- #################################################################################### -->
    <Package ID="1" DefaultComponent="ODBC">

      <!-- Errors and warnings in general operation. --> 
      <!-- Error thrown when an unexpected exception is caught. --> 
      <Error Key="GenErr" NativeErrorCode="10000" _locID="1.GenErr">General error: Unexpected exception caught.</Error>

      <!-- Same as GenErr, but allows for a custom message (say, from an std::exception) --> 
      <Error Key="GenErr1" Params="1" NativeErrorCode="10001" _locID="1.GenErr1">General error: %1%</Error>

      <!-- Error thrown when a std::bad_alloc exception is caught. --> 
      <Error Key="MemAllocErr" NativeErrorCode="10010" _locID="1.MemAllocErr">Memory allocation error: std::bad_alloc exception caught.</Error>

      <!-- Error thrown when ODBC functions are executed out of the allowed sequence as specified in the ODBC specification. --> 
      <Error Key="FuncSeqErr" NativeErrorCode="10020" _locID="1.FuncSeqErr">ODBC function executed out of allowable sequence.</Error>

      <!-- Error thrown when statement is invalid or not found. --> 
      <Error Key="InvalidStmt" NativeErrorCode="10040" _locID="1.InvalidStmt">Statement invalid or not found.</Error>

      <!-- Error thrown when connection is invalid or not found. --> 
      <Error Key="InvalidConn" NativeErrorCode="10050" _locID="1.InvalidConn">Connection invalid or not found.</Error>

      <!-- Error thrown when descriptor is invalid or not found. --> 
      <Error Key="InvalidAppDesc" NativeErrorCode="10060" _locID="1.InvalidAppDesc">Application descriptor invalid or not found.</Error>

      <!-- Error thrown when explicit application descriptor is invalid or not found. --> 
      <Error Key="InvalidExplAppDesc" NativeErrorCode="10070" _locID="1.InvalidExplAppDesc">Explicit application descriptor invalid or not found.</Error>

      <!-- Error thrown when query manager is invalid or not found. --> 
      <Error Key="InvalidQueryMgr" NativeErrorCode="10080" _locID="1.InvalidQueryMgr">Query manager invalid or not found.</Error>

      <!-- Error thrown when execution results are invalid or not found. --> 
      <Error Key="InvalidExecResults" NativeErrorCode="10090" _locID="1.InvalidExecResults">Execution results invalid or not found.</Error>

      <!-- Errors and warnings with diagnostics reporting. --> 
      <!-- Error thrown when an invalid diagnostic identifier is used. --> 
      <Error Key="InvalidDiagIdent" NativeErrorCode="10110" _locID="1.InvalidDiagIdent">Invalid diagnostic identifier used.</Error>

      <!-- Error thrown when requesting for a diagnostic field in binary format while no binary diagnostic fields exist. -->
      <Error Key="NoBinaryDiagFields" NativeErrorCode="10120" _locID="1.NoBinaryDiagFields">Unable to return diagnostic field in requested binary format: no binary diagnostic fields exist.</Error>


      <!-- Errors and warnings with the provided buffer and buffer length. --> 
      <!-- Error thrown when an invalid string or buffer length is provided by the application. --> 
      <Error Key="InvalidStrOrBuffLen" NativeErrorCode="10130" _locID="1.InvalidStrOrBuffLen">Invalid string or buffer length provided by the application.</Error>

      <!-- Warning posted when an output string is right truncated to fit into the output buffer. --> 
      <Error Key="StrRightTruncWarn" NativeErrorCode="10160" _locID="1.StrRightTruncWarn">Output string data right truncation: string data is too big for the output data buffer and has been truncated.</Error>

      <!-- Error thrown when string data is too big for the driver's data buffer. --> 
      <Error Key="StrRightTruncInsufBufferErr" NativeErrorCode="10170" _locID="1.StrRightTruncInsufBufferErr">String data right truncation on data from data source: string data is too big for the driver's data buffer.</Error>

      <!-- Error thrown when an invalid output buffer is provided. --> 
      <Error Key="InvalidOutputBuff" NativeErrorCode="10180" _locID="1.InvalidOutputBuff">Invalid output buffer provided.</Error>

      <!-- Error thrown when there is an invalid string truncation. --> 
      <Error Key="InvalidStrTrunc" NativeErrorCode="10190" _locID="1.InvalidStrTrunc">Invalid string truncation.</Error>


      <!-- Error and warnings with Attributes. --> 
      <!-- Error thrown when the attribute type specified is not supported for the current operation. --> 
      <Error Key="AttrTypeNotSupported" NativeErrorCode="10200" _locID="1.AttrTypeNotSupported">Attribute type not supported for current operation.</Error>

      <!-- Error thrown when the attribute identifier specified is invalid or not supported. --> 
      <Error Key="InvalidAttrIdent" Params="1" NativeErrorCode="10210" _locID="1.InvalidAttrIdent">Attribute identifier invalid or not supported: %1%</Error>

      <!-- Error thrown when setting the value of a read-only attribute. --> 
      <Error Key="CannotSetReadOnlyAttr" NativeErrorCode="10220" _locID="1.CannotSetReadOnlyAttr">Cannot set a read-only attribute.</Error>

      <!-- Error thrown when failed to retrieve an attribute value. --> 
      <Error Key="AttrValNotFound" NativeErrorCode="10230" _locID="1.AttrValNotFound">Cannot obtain attribute value.</Error>

      <!-- Error thrown when setting the implementation descriptor handle, a statement's implementation descriptor cannot be replaced. --> 
      <Error Key="CannotSetImpDescHandle" NativeErrorCode="10240" _locID="1.CannotSetImpDescHandle">Cannot change a statement's implementation descriptor handle.</Error>

      <!-- Error thrown when setting the value of SQL_ATTR_ASYNC_ENABLE statement attribute when driver does not support this operation. --> 
      <Error Key="SetAsyncEnabNotSupported" NativeErrorCode="10250" _locID="1.SetAsyncEnabNotSupported">Setting SQL_ATTR_ASYNC_ENABLE attribute not supported.</Error>

      <!-- Error thrown when failed to obtain a connection attribute that is required to check if the current operation is valid. --> 
      <Error Key="ObtainCheckingConnAttrFailed" NativeErrorCode="10260" _locID="1.ObtainCheckingConnAttrFailed">Could not obtain a required connection attribute to check if current operation is valid.</Error>

      <!-- Error thrown when changing the option to enable auto population of IPD while driver does not support IPD auto population. --> 
      <Error Key="AutoPopIpdNotSupported" NativeErrorCode="10270" _locID="1.AutoPopIpdNotSupported">Auto-population of IPD (Implementation Parameter Descriptor)is not supported.</Error>

      <!-- Error thrown when setting an attribute to a value that is invalid. --> 
      <Error Key="InvalidAttrVal" NativeErrorCode="10280" _locID="1.InvalidAttrVal">Invalid attribute value.</Error>

      <!-- Warning posted when setting an attribute value that is not supported or invalid, and the driver was able to substitute a similar value. --> 
      <Error Key="OptAttrValChangedWarn" NativeErrorCode="10290" _locID="1.OptAttrValChangedWarn">Attribute value not supported or invalid. A similar attribute value was substituted. To see the substituted value, check the current attribute value.</Error>

      <!-- Error thrown when failing to revert a temporarily substituted attribute value back to its original value. --> 
      <Error Key="RevertAttrValueToOrigFailed" NativeErrorCode="10300" _locID="1.RevertAttrValueToOrigFailed">Could not revert temporary attribute value back to original value.</Error>

      <!-- Error thrown when failing to obtain a default value for a statement attribute during statement creation. --> 
      <Error Key="ObtainDefaultStmtAttrValueFailed" NativeErrorCode="10310" _locID="1.ObtainDefaultStmtAttrValueFailed">Could not obtain default statement attribute value.</Error>

      <!-- Error thrown when setting an explicit application descriptor handle on a statement that is not from the statement's parent connection. --> 
      <Error Key="ExplAppDescHandleNotFromSameConn" NativeErrorCode="10320" _locID="1.ExplAppDescHandleNotFromSameConn">Explicit application descriptor handle not from the same connection as the target statement.</Error>

      <!-- Error thrown when setting an implicit application descriptor handle on a statement but the descriptor was not one of the target statement's original implicit application descriptors. --> 
      <Error Key="ImplicitAppDescHandleNotOrig" NativeErrorCode="10330" _locID="1.ImplicitAppDescHandleNotOrig">Implicit application descriptor handle is not an original implicit application descriptor of the target statement.</Error>

      <!-- Error and warnings with establishing connection to data source. -->
      <!-- Error thrown when the connection string is not of valid form. -->
      <Error Key="InvalidConnStr" NativeErrorCode="10360" _locID="1.InvalidConnStr">Invalid connection string.</Error>

      <!-- Error thrown when the connection string does not contain information requested by the driver. -->
      <Error Key="InvalidConnStrAttr" NativeErrorCode="10370" _locID="1.InvalidConnStrAttr">Invalid connection string attribute: does not match driver-requested information.</Error>

      <!-- Error thrown when unable to establish a connection with the data source. -->
      <Error Key="UnableToEstConn" Params="1" NativeErrorCode="10380" _locID="1.UnableToEstConn">Unable to establish connection with data source. Missing settings: %1%</Error>

      <!-- Error thrown when failed to obtain connection information through the driver provided dialog box. -->
      <Error Key="UpdateConnSettingsWithDiaglogFailed" NativeErrorCode="10390" _locID="1.UpdateConnSettingsWithDiaglogFailed">Update connection settings with dialog prompt failed.</Error>

      <!-- Error thrown when performing an operation that requires an established connection but no connection has been established yet. -->
      <Error Key="NoEstConn" NativeErrorCode="10400" _locID="1.NoEstConn">Current operation requires established connection but no connection has been established yet.</Error>

      <!-- Error thrown when trying to establish a connection but a connection already exist. -->
      <Error Key="ConnAlreadyEst" NativeErrorCode="10410" _locID="1.ConnAlreadyEst">Connection is already established.</Error>

      <!-- Error thrown when data source did not provide a valid response. -->
      <Error Key="DataSourceDidNotGiveProperResp" NativeErrorCode="10420" _locID="1.DataSourceDidNotGiveProperResp">Data source did not provide a proper response.</Error>

      <!-- Error thrown when application did not provide enough information to establish a connection to the data source but application specified that driver should not prompt application for more information. -->
      <Error Key="NotEnoughConnInfoButDriverNoPrompt" Params="1" NativeErrorCode="10430" _locID="1.NotEnoughConnInfoButDriverNoPrompt">Not enough information provided to establish a connection to the data source, and prompt for more information has been disabled. Missing required settings: %1%</Error>

      <!-- Error thrown when driver complete flag is invalid or not supported. -->
      <Error Key="InvalidDriverComplFlag" NativeErrorCode="10440" _locID="1.InvalidDriverComplFlag">Driver completion flag invalid or not supported.</Error>

      <!-- Error thrown when driver needs an indicator buffer to indicate NULL output data to the application but the application did not provide such buffer. -->
      <Error Key="NullIndPtrNotSupplied" NativeErrorCode="10450" _locID="1.NullIndPtrNotSupplied">Indicator pointer is required by the driver to indicate NULL output data, but is not provided.</Error>

      <!-- Error thrown when data conversion could not complete properly. -->
      <Error Key="DataConvError" NativeErrorCode="10460" _locID="1.DataConvError">Data conversion error.</Error>

      <!-- Error thrown when data conversion is not supported. -->
      <Error Key="DataConvNotSupported" NativeErrorCode="10470" _locID="1.DataConvNotSupported">Data conversion not supported.</Error>

      <!-- Error thrown when fetch orientation is not compatible with current settings. -->
      <Error Key="FetchTypeNotSupported" NativeErrorCode="10480" _locID="1.FetchTypeNotSupported">Fetch type not supported, as fetch orientation is not compatible with current settings.</Error>

      <!-- Error thrown when cursor is in an invalid position for fetching data. -->
      <Error Key="InvalidCursorPos" NativeErrorCode="10490" _locID="1.InvalidCursorPos">Cursor not positioned within result set.</Error>

      <!-- Error thrown when cursor is forward-only and SetPos is called while on a valid row. -->
      <Error Key="InvalidForwardSetPosOper" NativeErrorCode="10495" _locID="1.InvalidForwardSetPosOper">SQLSetPos is an invalid operation when the cursor is forward-only.</Error>

      <!-- Error thrown when cursor is not of a supported type. -->
      <Error Key="InvalidCursorType" NativeErrorCode="10500" _locID="1.InvalidCursorType">Cursor type invalid or not supported.</Error>

      <!-- Error thrown when cursor is in an invalid state. -->
      <Error Key="InvalidCursorState" NativeErrorCode="10510" _locID="1.InvalidCursorState">Invalid cursor state.</Error>

      <!-- Error thrown when there is no more data left to fetch. -->
      <Error Key="NoMoreDataToFetch" NativeErrorCode="10530" _locID="1.NoMoreDataToFetch">No more data left to fetch.</Error>

      <!-- Error thrown when getting data that has already been fetched, but current settings do not allow this behavior. -->
      <Error Key="NotAllowedToGetSpecifiedColumn" NativeErrorCode="10540" _locID="1.NotAllowedToGetSpecifiedColumn">Not allowed to get data that was already fetched for the specified column.</Error>

      <!-- Error thrown when requesting a column in the result set but no matching column is found. -->
      <Error Key="InvalidColNumInResultSet" NativeErrorCode="10550" _locID="1.InvalidColNumInResultSet">Invalid result set column number: no matching column found.</Error>

      <!-- Error thrown when checking the status of a fetched row but the status is invalid and not recognized. -->
      <Error Key="InvalidRowStatus" NativeErrorCode="10560" _locID="1.InvalidRowStatus">Invalid row status detected after fetching operation.</Error>

      <!-- Error thrown when changing types between multipart SQLGetData() calls. -->
      <Error Key="ChangeTypesInMultipartSQLGetDataNotSupported" NativeErrorCode="10570" _locID="1.ChangeTypesInMultipartSQLGetDataNotSupported">Changing types between multipart SQLGetData() calls is not supported.</Error>

      <!-- Error thrown when the source data is invalid (i.e. null when it shouldn't be. -->
      <Error Key="InvalidSrcData" NativeErrorCode="10580" _locID="1.InvalidSrcData">Source data is invalid.</Error>

      <!-- Error thrown when there is no more data to get. -->
      <Error Key="NoMoreDataToGet" NativeErrorCode="10590" _locID="1.NoMoreDataToGet">There is no more data to get.</Error>

      <!-- Error thrown when the conversion strategy is invalid (i.e. null when it shouldn't be). -->
      <Error Key="InvalidStrategy" NativeErrorCode="10600" _locID="1.InvalidStrategy">Conversion strategy is invalid.</Error>

      <!-- Error thrown when the conversion strategy is not supported. -->
      <Error Key="StrategyNotSupported" NativeErrorCode="10610" _locID="1.StrategyNotSupported">Conversion strategy is unsupported.</Error>

      <!-- Error thrown when a conversion is attempted when there is more data. -->
      <Error Key="CannotConvWhileHasMoreData" NativeErrorCode="10620" _locID="1.CannotConvWhileHasMoreData">Cannot convert when there is more data.</Error>

      <!-- Error thrown when the result of a conversion is invalid. -->
      <Error Key="InvalidConvResult" NativeErrorCode="10630" _locID="1.InvalidConvResult">Invalid conversion result.</Error>

      <!-- Error thrown when a flush fails to clear the data. -->
      <Error Key="FlushFailed" NativeErrorCode="10640" _locID="1.FlushFailed">Flush failed to clear data.</Error>

      <!-- Error thrown when execution expects a result set but no result set is available from the DSII. -->
      <Error Key="NoAvailableResultSet" NativeErrorCode="10651" _locID="1.NoAvailableResultSet">No result set is available after execute, but a result set was available after prepare.</Error>

      <!-- Error thrown when a Driver Manager calls SQLConnect without providing a valid DSN. -->
      <Error Key="InvalidDSN" NativeErrorCode="10652" _locID="1.InvalidDSN">DSN must not be an empty string as per ODBC specifications. The driver manager must provide a valid DSN value.</Error>
      
      <!-- Error and warnings with descriptors. -->
      <!-- Error thrown when requesting a bookmark column but bookmark columns are not supported. -->
      <Error Key="BookmarkColumnNotSupported" NativeErrorCode="10660" _locID="1.BookmarkColumnNotSupported">Bookmark column not supported.</Error>

      <!-- Error thrown when requesting a descriptor record or its information, but the descriptor record cannot be found -->
      <Error Key="InvalidDescIndex" NativeErrorCode="10670" _locID="1.InvalidDescIndex">Invalid descriptor index, descriptor record does not exist, or descriptor record was not properly initialized.</Error>

      <!-- Error thrown when requesting a descriptor field that is not supported or is invalid. -->
      <Error Key="InvalidDescFieldIdent" NativeErrorCode="10680" _locID="1.InvalidDescFieldIdent">Descriptor field identifier invalid or not supported.</Error>

      <!-- Error thrown when descriptor records are not sequential during query execution. -->
      <Error Key="DescRecNotSeq" NativeErrorCode="10690" _locID="1.DescRecNotSeq">Expected descriptor record does not exist during query execution.</Error>

      <!-- Error thrown when retrieving the SQL_DESC_COUNT field that is zero for a IRD. -->
      <Error Key="InvalidDescCount" NativeErrorCode="10700" _locID="1.InvalidDescCount">Invalid descriptor count field: no count to be returned.</Error>

      <!-- Error thrown when setting a read-only descriptor field. -->
      <Error Key="ReadOnlyDescField" NativeErrorCode="10710" _locID="1.ReadOnlyDescField">Read-only descriptor field.</Error>

      <!-- Error thrown when registering or unregistering a listener (statement) on a non-explicit descriptor. -->
      <Error Key="CannotAssocNonExpDescWithDeleteListener" NativeErrorCode="10720" _locID="1.CannotAssocNonExpDescWithDeleteListener">Cannot associate non-explicit descriptors with descriptor listeners used for deletion cleanup.</Error>

      <!-- Error thrown when getting the parent connection of a non-explicit descriptor. -->
      <Error Key="CannotGetParentConnOnNonExpDesc" NativeErrorCode="10730" _locID="1.CannotGetParentConnOnNonExpDesc">Cannot get parent connection on a non-explicit descriptor.</Error>

      <!-- Error thrown when dropping descriptor record of an implementation row descriptor. -->
      <Error Key="CannotDropRecOfImplRowDesc" NativeErrorCode="10740" _locID="1.CannotDropRecOfImplRowDesc">Cannot drop record of an implementation row descriptor.</Error>

      <!-- Error thrown when an invalid or not supported datetime subcode identifier is given. -->
      <Error Key="InvalidDatetimeSubcodeIdent" NativeErrorCode="10750" _locID="1.InvalidDatetimeSubcodeIdent">Datetime subcode identifier invalid or not supported.</Error>

      <!-- Error thrown when an invalid or not supported interval subcode identifier is given. -->
      <Error Key="InvalidIntevalSubcodeIdent" NativeErrorCode="10760" _locID="1.InvalidIntevalSubcodeIdent">Interval subcode identifier invalid or not supported.</Error>

      <!-- Error thrown when requesting a descriptor field that is not supported or invalid. -->
      <Error Key="DescFieldNotSupported" NativeErrorCode="10770" _locID="1.DescFieldNotSupported">Descriptor field invalid or not supported.</Error>

      <!-- Error thrown when using a non-string method to get a string descriptor field. -->
      <Error Key="CannotGetStrDescFieldInNonStrMethod" NativeErrorCode="10780" _locID="1.CannotGetStrDescFieldInNonStrMethod">Invalid use of non-string method to get string descriptor field.</Error>

      <!-- Error thrown when specifying a descriptor field type that is not valid or not supported -->
      <Error Key="InvalidDescFieldType" NativeErrorCode="10790" _locID="1.InvalidDescFieldType">Descriptor field type invalid or not supported.</Error>

      <!-- Error thrown when the specified descriptor record cannot be found. -->
      <Error Key="DescRecNotFound" NativeErrorCode="10800" _locID="1.DescRecNotFound">Descriptor record not found.</Error>

      <!-- Error thrown when setting SQL_DESC_UNNAMED to SQL_NAMED which is not allowed. -->
      <Error Key="DescUnnamedNotAllowed" NativeErrorCode="10810" _locID="1.DescUnnamedNotAllowed">Not allowed to set SQL_DESC_UNNAMED to SQL_NAMED.</Error>

      <!-- Error thrown when performing an operation which requires the statement to be prepared but is not. -->
      <Error Key="StmtNotPrep" NativeErrorCode="10820" _locID="1.StmtNotPrep">Statement not prepared.</Error>

      <!-- Error thrown when setting or getting a descriptor field value that is not supported. -->
      <Error Key="DescFieldValueNotSupported" Params="2" NativeErrorCode="10830" _locID="1.DescFieldValueNotSupported">Descriptor field %1% does not support the value %2%.</Error>

      <!-- Error thrown when application modifies an implementation row descriptor -->
      <Error Key="CannotModImpRowDesc" NativeErrorCode="10840" _locID="1.CannotModImpRowDesc">Cannot modify implementation row descriptors.</Error>

      <!-- Error thrown when setting the SQL_DESC_ALLOC_TYPE descriptor field. -->
      <Error Key="CannotSetDescAllocType" NativeErrorCode="10850" _locID="1.CannotSetDescAllocType">Cannot set descriptor SQL_DESC_ALLOC_TYPE.</Error>

      <!-- Error thrown when an illegal descriptor type is detected. -->
      <Error Key="IllegalDescType" NativeErrorCode="10860" _locID="1.IllegalDescType">Illegal descriptor type.</Error>

      <!-- Error thrown when an illegal descriptor concise type is detected -->
      <Error Key="IllegalDescConciseType" NativeErrorCode="10870" _locID="1.IllegalDescConciseType">Illegal descriptor concise type.</Error>

      <!-- Error thrown when an invalid or not supported datetime interval code is given. -->
      <Error Key="InvalidDatetimeCodeIdent" NativeErrorCode="10880" _locID="1.InvalidDatetimeCodeIdent">Datetime interval code invalid or not supported.</Error>

      <!-- Error thrown when an invalid or not supported interval code is given. -->
      <Error Key="InvalidIntervalCode" NativeErrorCode="10890" _locID="1.InvalidIntervalCode">Interval code invalid or not supported.</Error>


      <!-- Error and warnings with SQL statement execution. -->
      <!-- Error thrown when reading from an output parameter. -->
      <Error Key="CannotReadFromOutputParam" NativeErrorCode="10900" _locID="1.CannotReadFromOutputParam">Cannot read from output parameter.</Error>

      <!-- Error thrown when reading from a default input parameter. -->
      <Error Key="CannotReadFromDefaultParam" NativeErrorCode="10910" _locID="1.CannotReadFromDefaultParam">No data can be obtained from a default input parameter.</Error>

      <!-- Error thrown when reading from an input parameter which value has already been pushed down. -->
      <Error Key="CannotReadFromPushedParam" NativeErrorCode="10920" _locID="1.CannotReadFromPushedParam">No data can be obtained from an input parameter whose value has already been pushed down.</Error>

      <!-- Error thrown when writing to a default output parameter. -->
      <Error Key="WriteToDefaultParam" NativeErrorCode="10930" _locID="1.WriteToDefaultParam">Cannot write to a default parameter.</Error>

      <!-- Error thrown when writing to an input parameter -->
      <Error Key="WriteToInputParam" NativeErrorCode="10940" _locID="1.WriteToInputParam">Cannot write to an input parameter.</Error>

      <!-- Error thrown when received an execute result status code that is not recognizable. -->
      <Error Key="InvalidExecStatusCode" NativeErrorCode="10950" _locID="1.InvalidExecStatusCode">Execute result status code is invalid or not supported.</Error>

      <!-- Error thrown when sending concatenated data that is not binary nor character. -->
      <Error Key="SendNonCharBinaryConcatData" NativeErrorCode="10970" _locID="1.SendNonCharBinaryConcatData">Cannot concatenate and send data that is not character or binary.</Error>

      <!-- Error thrown when sending concatenated data that is a default or null parameter. -->
      <Error Key="SendConcatDataForDefaultOrNullParam" NativeErrorCode="10980" _locID="1.SendConcatDataForDefaultOrNullParam">Cannot concatenate data for a default or null parameter.</Error>

      <!-- Error thrown when getting SQLGetInfo field which is not supported. -->
      <Error Key="InvalidGetInfoField" NativeErrorCode="10990" _locID="1.InvalidGetInfoField">SQLGetInfo field is invalid or not supported.</Error>

      <!-- Error thrown when getting query executor from catalog query manager.  Catalog functions are already executed thus has not query executor. -->
      <Error Key="NoQueryExecutor" NativeErrorCode="11000" _locID="1.NoQueryExecutor">No query executor exists for catalog query manager.</Error>

      <!-- Error thrown when there is no data-at-execution parameter detected for query executor. -->
      <Error Key="NoDataAtExecParameter" NativeErrorCode="11010" _locID="1.NoDataAtExecParameter">No data-at-execution parameter.</Error>

      <!-- Error thrown when querying a parameter source during auto population. -->
      <Error Key="CannotQueryParmSrcDuringPopulate" NativeErrorCode="11020" _locID="1.CannotQueryParmSrcDuringPopulate">Cannot query information about parameter source during parameter auto-population.</Error>

      <!-- Error thrown when setting fields of a parameter source during parameter data pushing. -->
      <Error Key="CannotSetParmSrcAttrDuringPushData" NativeErrorCode="11030" _locID="1.CannotSetParmSrcAttrDuringPushData">Cannot set parameter source attributes during parameter data pushing.</Error>

      <!-- Error thrown when querying push value status while not performing execution.  -->
      <Error Key="PushValueStatusUnknown" NativeErrorCode="11040" _locID="1.PushValueStatusUnknown">Push value status can only be queried during execution.</Error>

      <!-- Error thrown when registering a parameter but not allowed in current state of execution. -->
      <Error Key="ParamRegistNotPermit" NativeErrorCode="11050" _locID="1.ParamRegistNotPermit">Parameter registration not permitted.</Error>

      <!-- Error thrown when invalid parameter index used for parameter registration. -->
      <Error Key="InvalidParamRegistIndex" NativeErrorCode="11060" _locID="1.InvalidParamRegistIndex">Invalid parameter index used for registration.</Error>

      <!-- Error thrown when descriptor field value is not recognizable. -->
      <Error Key="DescFieldNotRecg" NativeErrorCode="11070" _locID="1.DescFieldNotRecg">Descriptor field value not of recognized value.</Error>

      <!-- Error thrown when parameter type is invalid or not supported  -->
      <Error Key="InvalidParameterType" NativeErrorCode="11080" _locID="1.InvalidParameterType">Parameter type invalid or not supported.</Error>

      <!-- Error thrown when setting fields of a parameter source during parameter execution. -->
      <Error Key="CannotSetParmSrcAttrDuringExecution" NativeErrorCode="11090" _locID="1.CannotSetParmSrcAttrDuringExecution">Cannot set parameter source attributes during execution.</Error>


      <!-- Error and warnings with connection and statement. -->
      <!-- Error thrown when setting a cursor name that is longer than the maximum limit. -->
      <Error Key="CursorNameTooLong" NativeErrorCode="11100" _locID="1.CursorNameTooLong">Cursor name too long.</Error>

      <!-- Error thrown when setting a cursor name that is already in use. -->
      <Error Key="DuplicateCursorName" NativeErrorCode="11110" _locID="1.DuplicateCursorName">Duplicate cursor name.</Error>

      <!-- Error thrown when there are outstanding transactions when attempting to disconnect. -->
      <Error Key="OutstandingTransDuringDisconn" NativeErrorCode="11120" _locID="1.OutstandingTransDuringDisconn">Outstanding transactions during disconnect.</Error>

      <!-- Error thrown when using a connection to allocate a resource that is not statement nor descriptor. -->
      <Error Key="AllocNonStmtDescInConn" NativeErrorCode="11130" _locID="1.AllocNonStmtDescInConn">Cannot use a connection to allocate a non-statement and non-descriptor resource.</Error>

      <!-- Error thrown when using a connection to free a resource that is not statement nor descriptor. -->
      <Error Key="FreeNonStmtDescInConn" NativeErrorCode="11140" _locID="1.FreeNonStmtDescInConn">Cannot use a connection to free a non-statement and non-descriptor resource.</Error>

      <!-- Error thrown when freeing an implicit application descriptor. -->
      <Error Key="FreeImplicitAppDesc" NativeErrorCode="11150" _locID="1.FreeImplicitAppDesc">Cannot free an implicit application descriptor.</Error>

      <!-- Error thrown when dropping an implicit application descriptor from its parent statement. -->