<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Messages[<!ELEMENT Messages (Package*)>

<!ELEMENT Package (Error*)>
<!ATTLIST Package ID CDATA #REQUIRED>
<!ATTLIST Package DefaultComponent CDATA #REQUIRED>

<!ELEMENT Error (#PCDATA)>
<!ATTLIST Error Key CDATA #REQUIRED>
<!ATTLIST Error _locID CDATA "0">
<!ATTLIST Error Component CDATA #IMPLIED>
<!ATTLIST Error NativeErrorCode CDATA #REQUIRED>
<!ATTLIST Error Params CDATA "0">]>

<Messages>
    <!-- SQL_ENGINE_ERROR ERRORS (30000 to 39999) -->
    <Package ID="4" DefaultComponent="SQLEngine">

        <!-- GENERAL ERRORS (30000 to 30999) -->

        <!-- [HY000]: General logic error. -->
        <Error Key="LogicError" Params="2" NativeErrorCode="30000" _locID="4.LogicError">Logic error [%1%: %2%].</Error>

        <!-- [HY000]: Invalid AE tree found. -->
        <Error Key="InvalidAET" Params="2" NativeErrorCode="30010" _locID="4.InvalidAET">Invalid AE tree [%1%: %2%].</Error>

        <!-- [HY000]: Invalid parse tree found. -->
        <Error Key="InvalidParseTree" Params="2" NativeErrorCode="30040" _locID="4.InvalidParseTree">Invalid parse tree [%1%: %2%].</Error>

        <!-- [HY000]: Lexer/Scanner initialization failure. -->
        <Error Key="LexerScannerInitFail" NativeErrorCode="30050" _locID="4.LexerScannerInitFail">Lexer/Scanner initialization failure.</Error>

        <!-- [HY000]: Stored procedure not found. -->
        <Error Key="StoredProcedureNotFound" Params="1" NativeErrorCode="30070" _locID="4.StoredProcedureNotFound">Stored procedure not found: %1%</Error>

        <!-- [HY000]: Duplicate parameter index registered. -->
        <Error Key="DuplicateParameterIndex" Params="1" NativeErrorCode="30080" _locID="4.DuplicateParameterIndex">Duplicate parameter index registered for stored procedure: %1%</Error>

        <!-- [HY000]: Invalid parameter index registered. -->
        <Error Key="InvalidParameterIndex" Params="1" NativeErrorCode="30090" _locID="4.InvalidParameterIndex">Invalid parameter index registered for stored procedure: %1%</Error>

        <!-- [HY000]: Return value is registered at a position that isn't the first. -->
        <Error Key="InvalidReturnValueIndex" NativeErrorCode="30100" _locID="4.InvalidReturnValueIndex">Return values must have an index of 0.</Error>

        <!-- [HY000]: Invalid number of parameters supplied for stored procedure. -->
        <Error Key="InvalidNumberProcedureParameters" Params="3" NativeErrorCode="30110" _locID="4.InvalidNumberProcedureParameters">Invalid number of parameters for stored procedure '%1%'. Expected: %2%; Received: %3%</Error>

        <!-- [HY000]: Invalid number of results supplied by stored procedure. -->
        <Error Key="InvalidNumberStoredProcedureResults" NativeErrorCode="30120" _locID="4.InvalidNumberStoredProcedureResults">Stored procedures may only return one result.</Error>
      
        <!-- [HY000]: Output parameter cannot be a default parameter. -->
        <Error Key="InvalidDefaultParam" Params="1" NativeErrorCode="30130" _locID="4.InvalidDefaultParam">Stored procedure argument %1% cannot have a default value. Only input and input_output parameters can have a default value.</Error>
      
        <!-- [HY000]: SQL_DEFAULT_PARAM cannot be specified for a parameter that does not have a default value. -->
        <Error Key="DefaultSpecForNonDefaultParam" Params="1" NativeErrorCode="30140" _locID="4.DefaultSpecForNonDefaultParam">Parameter %1% cannot use a default value because it does not have a default value.</Error>

        <!-- [HY000]: Error thrown when an invalid data engine property is specified -->
        <Error Key="InvalidDataEngineProp" Params="1" NativeErrorCode="30141" _locID="4.InvalidDataEngineProp">Invalid data engine property: %1%</Error>

        <!-- [HY000]: Cannot create collator for language. -->
        <Error Key="CannotCreateCollator" Params="1" NativeErrorCode="30142" _locID="4.CannotCreateCollator">Cannot create collator for language: %1%</Error>

        <!-- [HY000]: Unsupported type found. -->
        <Error Key="TypeUnsupported" Params="1" NativeErrorCode="30160" _locID="4.TypeUnsupported">%1% is not supported.</Error>

        <!-- [HY000]: Trying to push fixed length data in parts. -->
        <Error Key="CantPushFixedLengthDataInParts" NativeErrorCode="30170" _locID="4.CantPushFixedLengthDataInParts">Fixed length parameter data cannot be pushed in parts.</Error>

        <!-- [HY000]: The pushed parameter data length exceeds the maximum. -->
        <Error Key="PushedParamDataTooLarge" NativeErrorCode="30180" _locID="4.PushedParamDataTooLarge">Pushed parameter data exceeds the maximum length.</Error>

        <!-- [HY000]: Cannot convert the pushed parameter value. -->
        <Error Key="InvalidPushedParamConversion" NativeErrorCode="30190" _locID="4.InvalidPushedParamConversion">Error converting pushed parameter value.</Error>

        <!-- [HY000]: Cannot query parameter values which may change during execution. -->
        <Error Key="CannotQueryParameterValueDuringPassdown" NativeErrorCode="30200" _locID="4.CannotQueryParameterValueDuringPassdown">Cannot query parameter value during passdown, as it may vary during execution.</Error>

        <!-- [HY000]: Encountered an error while trying to create table. -->
        <Error Key="CannotCreateTable" Params="1" NativeErrorCode="30210" _locID="4.CannotCreateTable">Encountered an error while trying to create table: %1%</Error>

        <!-- SQL Errors. (31000 to 39999) -->
        <!-- Sorted by SQLState and the keys. -->
      
        <!-- [07006]: General Restricted data type attribute violation errors. -->
        <Error Key="RestrictedDataTypeViolation" NativeErrorCode="31020" _locID="4.RestrictedDataTypeViolation">Restricted data type attribute violation.</Error>

        <!-- [07006]: Scalar function CONVERT does not support the specified conversion. -->
        <Error Key="ConvertConversionNotSupported" Params="2" NativeErrorCode="31040" _locID="4.ConvertConversionNotSupported">CONVERT does not support the specified conversion from %1% to %2%.</Error>

        <!-- MAINTENANCE NOTE: This translation needs to be reviewed -->
        <!-- [07006]: Scalar function CONVERT does not support the specified conversion. -->
        <Error Key="CastConversionNotSupported" Params="2" NativeErrorCode="31041" _locID="4.CastConversionNotSupported">CAST does not support the specified conversion from %1% to %2%.</Error>

        <!-- [07006]: Scalar function CONVERT does not support the FORMAT specification. -->
        <Error Key="CastFormatNotSupported" NativeErrorCode="31042" _locID="4.CastFormatNotSupported">CAST does not support the FORMAT clause.</Error>

        <!-- [21000]: Cardinality violation - Value SubQuery returns more than 1 value. -->
        <Error Key="InvalidValueSubQuery" NativeErrorCode="31050" _locID="4.InvalidValueSubQuery">Cardinality violation - value subquery returned more than one value.</Error>

        <!-- [21S01]: Insert value list degree doesn't match insert table degree. -->
        <Error Key="InvalidNumberInsertValues" Params="2" NativeErrorCode="31051" _locID="4.InvalidNumberInsertValues">The number of values to be inserted (%1%) does not match the number of columns (%2%) in the insert table.</Error>

        <!-- [22001]: String or binary data right truncation. -->
        <Error Key="RightDataTruncation" NativeErrorCode="31052" _locID="4.RightDataTruncation">String or binary data right truncation.</Error>

        <!-- [22003]: Max precision exceeded. -->
        <Error Key="MaxPrecisionExceeded" Params="2" NativeErrorCode="31060" _locID="4.MaxPrecisionExceeded">The number '%1%' exceeds the maximum precision allowed (%2%).</Error>

        <!-- [22003]: Domain value error for a scalar function. -->
        <Error Key="ScalarFnDomainError" Params="1" NativeErrorCode="31070" _locID="4.ScalarFnDomainError">Domain value out of range for '%1%' scalar function.</Error>

        <!-- [22003]: Range value error for a scalar function. -->
        <Error Key="ScalarFnRangeError" Params="1" NativeErrorCode="31080" _locID="4.ScalarFnRangeError">Result value out of range for '%1%' scalar function.</Error>

        <!-- [22003]: Year range value error for a scalar function. -->
        <Error Key="ScalarFnYearRangeError" Params="1" NativeErrorCode="31090" _locID="4.ScalarFnYearRangeError">Year value of %1% is out of range, allowable range is [-9999, 9999].</Error>

        <!-- [22003]: Negate minimum signed integer error. -->
        <Error Key="NegateMinSignedIntegerError" NativeErrorCode="31091" _locID="4.NegateMinSignedIntegerError">Negating the minimum value of a signed integer is invalid.</Error>

        <!-- [22012]: Division By Zero. -->
        <Error Key="DivisionByZero" NativeErrorCode="31100" _locID="4.DivisionByZero">Division by zero.</Error>

        <!-- [22015]: Leading interval precision exceeded. -->
        <Error Key="LeadingPrecisionExceeded" Params="1" NativeErrorCode="31101" _locID="4.LeadingPrecisionExceeded">Leading interval precision of %1% exceeded.</Error>

        <!-- [22015]: Leading interval precision out of range. -->
        <Error Key="LeadingPrecisionRangeError" NativeErrorCode="31102" _locID="4.LeadingPrecisionRangeError">Leading interval precision value must be in the range [0, 9].</Error>

        <!-- [22015]: Fractional seconds precision out of range. -->
        <Error Key="FractionalPrecisionRangeError" NativeErrorCode="31103" _locID="4.FractionalPrecisionRangeError">Fractional seconds precision value must be in the range [1, 9].</Error>

        <!-- [22018]: Comparing binary types are not supported. -->
        <Error Key="CompareBinaryTypesNotSupported" NativeErrorCode="31110" _locID="4.CompareBinaryTypesNotSupported">Comparing binary types is not supported.</Error>

        <!-- [22018]: Incompatible argument type for scalar function. -->
        <Error Key="IncompatibleArgTypeForScalarFn" Params="3" NativeErrorCode="31120" _locID="4.IncompatibleArgTypeForScalarFn">Incompatible argument type %1% for argument %2% of scalar function %3%.</Error>

        <!-- [22018]: Incompatible collations found. -->
        <Error Key="IncompatibleCollations" NativeErrorCode="31130" _locID="4.IncompatibleCollations">Incompatible collations found.</Error>

        <!-- [22018]: Incompatible types in predicate -->
        <Error Key="IncompatibleTypeInPredicate" NativeErrorCode="31140" _locID="4.IncompatibleTypeInPredicate">Incompatible types in predicate.</Error>

        <!-- [22018]: LIKE predicates requires character data types. -->
        <Error Key="LikePredicateRequiresCharTypes" NativeErrorCode="31150" _locID="4.LikePredicateRequiresCharTypes">LIKE predicates requires character data types.</Error>

        <!-- [22018]: Incompatible types in INSERT list. -->
        <Error Key="IncompatibleInsertType" Params="2" NativeErrorCode="31151" _locID="4.IncompatibleInsertType">Incompatible type for insertion: expected %1%, actual %2%.</Error>

        <!-- [22018]: Long data types in GROUP BY or ORDER BY are not supported. -->
        <Error Key="LOBInOrderByOrGroupBy" NativeErrorCode="31160" _locID="4.LOBInOrderByOrGroupBy">Long data types in GROUP BY or ORDER BY are not supported.</Error>

        <!-- [22018]: Literal conversion error for a scalar function. -->
        <Error Key="ScalarFnLiteralConvError" Params="1" NativeErrorCode="31161" _locID="4.ScalarFnLiteralConvError">Error converting '%1%' to numeric value for scalar function.</Error>

        <!-- [22018]: Integer literal conversion error for a scalar function. -->
        <Error Key="ScalarFnIntegerLiteralConvError" Params="1" NativeErrorCode="31162" _locID="4.ScalarFnIntegerLiteralConvError">Error converting '%1%' to integer numeric value for scalar function.</Error>

        <!-- [22019]: Invalid LIKE escape character. -->
        <Error Key="InvalidEscapeChar" Params="1" NativeErrorCode="31166" _locID="4.InvalidEscapeChar">Invalid LIKE escape clause '%1%'. Escape clause must consist of exactly one character.</Error>

        <!-- [22025]: Invalid LIKE escape sequence. -->
        <Error Key="InvalidEscapeSequence" NativeErrorCode="31167" _locID="4.InvalidEscapeSequence">Invalid LIKE ESCAPE sequence. Escape character must be followed by '%', '_', or another escape character.</Error>

        <!-- [42000]: Aggregate functions and subqueries are not allowed in the GROUP BY clause. -->
        <Error Key="AggrFnAndSubQueryInGroupBy" NativeErrorCode="31180" _locID="4.AggrFnAndSubQueryInGroupBy">Aggregate functions and subqueries are not allowed in a GROUP BY clause.</Error>

        <!-- [42000]: SQL syntax error (this is used by SQL Parser to indicate general syntax error). -->
        <Error Key="SyntaxError" NativeErrorCode="31181" _locID="4.SyntaxError">Syntax Error.</Error>

        <!-- [42000]: Aggregate functions in an ON clause not allowed. -->
        <Error Key="AggrFunctionInOn" NativeErrorCode="31190" _locID="4.AggrFunctionInOn">An aggregate function in an ON clause is not allowed, unless it is in a sub-query contained in the SELECT LIST or the HAVING clause and the column aggregating is an outer reference.</Error>

        <!-- [42000]: Aggregate functions in the WHERE clause not allowed. -->
        <Error Key="AggrFunctionInWhere" NativeErrorCode="31200" _locID="4.AggrFunctionInWhere">An aggregate function in the WHERE clause is not allowed, unless it is in a sub-query contained in the SELECT LIST or the HAVING clause and the column aggregating is an outer reference.</Error>

        <!-- [42000]: Aggregate function alias needed in the PIVOT clause. -->
        <Error Key="AggrFunctionAliasInPivot" NativeErrorCode="31201" _locID="4.AggrFunctionAliasInPivot">In the Pivot clause, if multiple aggregate functions are specified, then the alias name must be specified for at least all but one of the aggregate functions.</Error>

        <!-- [42000]: Number of values need to match number of columns in the PIVOT clause. -->
        <Error Key="PivotColumnValuesNumberMismatch" NativeErrorCode="31202" _locID="4.PivotColumnValuesNumberMismatch">The number of values does not match the number of columns in PIVOT IN CLAUSE.</Error>
        
        <!-- [42000]: The number of measure columns does not match the number of column references in the UNPIVOT IN clause. -->
        <Error Key="MeasureColumnNumberMismatch" NativeErrorCode="31203" _locID="4.MeasureColumnNumberMismatch">The number of measure columns does not match the number of column references in the UNPIVOT IN clause.</Error>
        
        <!-- [42000]: The number of unpivot columns does not match the number of column alias in the UNPIVOT IN clause. -->
        <Error Key="UnpivotColumnNumberMismatch" NativeErrorCode="31204" _locID="4.UnpivotColumnNumberMismatch">The number of unpivot columns does not match the number of column alias in the UNPIVOT IN clause.</Error>
        
        <!-- [42000]: Aggregate functions in neither the SELECT LIST nor the HAVING clause. -->
        <Error Key="AggrFunctionNotInSelListOrHaving" NativeErrorCode="31210" _locID="4.AggrFunctionNotInSelListOrHaving">An aggregate function containing an outer reference must be in the SELECT LIST or the HAVING clause.</Error>

        <!-- [42000]: Constant order by expression(s). -->
        <Error Key="ConstantOrderByExpression" NativeErrorCode="31220" _locID="4.ConstantOrderByExpression">An ORDER BY key may not be a constant expression.</Error>

        <!-- [42000]: Correlated sub-query not allowed in HAVING. -->
        <Error Key="CorrSubQueryNotAllowedInHaving" NativeErrorCode="31230" _locID="4.CorrSubQueryNotAllowedInHaving">Correlated sub-query not allowed in HAVING clause.</Error>

        <!-- [42000]: Duplicated column name for table. -->
        <Error Key="DuplicatedColumnName" Params="2" NativeErrorCode="31240" _locID="4.DuplicatedColumnName">Duplicated column name '%1%' was specified in '%2%'.</Error>

        <!-- [42000]: Duplicated column name for update list. -->
        <Error Key="DuplicatedUpdateColumnName" Params="1" NativeErrorCode="31241" _locID="4.DuplicatedUpdateColumnName">Duplicate column name '%1%' was specified in update list.</Error>

        <!-- [42000]: Dynamic parameter not allowed. -->
        <Error Key="DynParamNotAllowed" Params="1" NativeErrorCode="31250" _locID="4.DynParamNotAllowed">Dynamic parameter not allowed in %1%.</Error>

        <!-- [42000]: Expression Not Row-based in GROUP BY clause. -->
        <Error Key="ExprInGroupByNotRowBased" NativeErrorCode="31260" _locID="4.ExprInGroupByNotRowBased">Every expression in the GROUP BY clause must contain at least one column reference, and all column references may not refer to an outer scope.</Error>

        <!-- [42000]: IF conditions are found in non-select list. -->
        <Error Key="IfCondInNonSelectList" Params="0" NativeErrorCode="31270" _locID="4.IfCondInNonSelectList">IF conditions must be in select list.</Error>

        <!-- [42000]: Incompatible binary operand types. -->
        <Error Key="IncompatibleBinaryOperandTypes" Params="3" NativeErrorCode="31280" _locID="4.IncompatibleBinaryOperandTypes">Operand types %1% and %2% are incompatible for the %3% operator.</Error>

        <!-- [42000]: Incompatible union column types. -->
        <Error Key="IncompatibleUnionColumnTypes" Params="2" NativeErrorCode="31281" _locID="4.IncompatibleUnionColumnTypes">Union columns %1% and %2% have incompatible types.</Error>

        <!-- [42000]: Incompatible set column types. -->
        <Error Key="IncompatibleSetColumnTypes" Params="3" NativeErrorCode="31282" _locID="4.IncompatibleSetColumnTypes">Matched columns must be convertible in result sets combined with %1%. %2% and %3% are not convertible.</Error>

        <!-- [42000]: Incompatible CASE result types. -->
        <Error Key="IncompatibleCaseResultTypes" Params="1" NativeErrorCode="31283" _locID="4.IncompatibleCaseResultTypes">Result types for CASE statements must be convertible. The types %1% are not mutually convertible.</Error>
        
        <!-- [42000]: Incompatible column types. -->
        <Error Key="IncompatibleColumnTypes" Params="1" NativeErrorCode="31284" _locID="4.IncompatibleColumnTypes">The column types %1% are not mutually convertible.</Error>

        <!-- [42000]: Incompatible except column types. -->
        <Error Key="IncompatibleExceptColumnTypes" Params="2" NativeErrorCode="31285" _locID="4.IncompatibleExceptColumnTypes">Except columns %1% and %2% have incompatible types.</Error>
      
        <!-- [42000]: Incompatible intersect column types. -->
        <Error Key="IncompatibleIntersectColumnTypes" Params="2" NativeErrorCode="31287" _locID="4.IncompatibleIntersectColumnTypes">Intersect columns %1% and %2% have incompatible types.</Error>

        <!-- [42000]: Invalid collation name found. -->
        <Error Key="InvalidCollationName" Params="1" NativeErrorCode="31290" _locID="4.InvalidCollationName">'%1%' is not a valid collation name.</Error>

        <!-- [42000]: Invalid column prefix. -->
        <Error Key="InvalidColumnPrefix" Params="1" NativeErrorCode="31300" _locID="4.InvalidColumnPrefix">Invalid column prefix: %1%.</Error>

        <!-- [42000]: Invalid operand type for SET function. -->
        <Error Key="InvalidOperandTypeForSetFn" Params="2" NativeErrorCode="31310" _locID="4.InvalidOperandTypeForSetFn">Operand type %1% is invalid for the SET operator '%2%'.</Error>

        <!-- [42000]: Invalid order by expression(s). -->
        <Error Key="InvalidOrderByExpression" NativeErrorCode="31320" _locID="4.InvalidOrderByExpression">Invalid ORDER BY key. Keys must be either unsigned integers, or expressions that are not case expressions, IF conditions, parameters or sub-queries.</Error>

        <!-- [42000]: Invalid sort column. -->
        <Error Key="InvalidOrderByColumn" NativeErrorCode="31321" _locID="4.InvalidOrderByColumn">ORDER BY not allowed for %1%.</Error>

        <!-- [42000]: Invalid number of arguments for a scalar function. -->
        <Error Key="InvalidScalarFnArgCount" Params="1" NativeErrorCode="31330" _locID="4.InvalidScalarFnArgCount">Invalid argument count for scalar function %1%.</Error>

        <!-- [42000]: Invalid scalar function or procedure name. -->
        <Error Key="InvalidScalarFnName" Params="1" NativeErrorCode="31340" _locID="4.InvalidScalarFnName">%1% is not a valid scalar function or procedure call.</Error>

        <!-- [42000]: Second argument invalid for CONVERT. -->
        <Error Key="InvalidSecondArgForConvertFn" NativeErrorCode="31350" _locID="4.InvalidSecondArgForConvertFn">Second argument for CONVERT is not a valid SQL_* type name.</Error>

        <!-- [42000]: First argument invalid for TIMESTAMPADD. -->
        <Error Key="InvalidFirstArgForTSAddFn" NativeErrorCode="31351" _locID="4.InvalidFirstArgForTSAddFn">The first argument for TIMESTAMPADD is invalid. Expected one of SQL_TSI_FRAC_SECOND, SQL_TSI_SECOND, SQL_TSI_MINUTE, SQL_TSI_HOUR, SQL_TSI_DAY, SQL_TSI_WEEK, SQL_TSI_MONTH, SQL_TSI_QUARTER, or SQL_TSI_YEAR.</Error>

        <!-- [42000]: First argument invalid for TIMESTAMPDIFF. -->
        <Error Key="InvalidFirstArgForTSDiffFn" NativeErrorCode="31352" _locID="4.InvalidFirstArgForTSDiffFn">The second argument for TIMESTAMPDIFF is invalid. Expected one of SQL_TSI_FRAC_SECOND, SQL_TSI_SECOND, SQL_TSI_MINUTE, SQL_TSI_HOUR, SQL_TSI_DAY, SQL_TSI_WEEK, SQL_TSI_MONTH, SQL_TSI_QUARTER, or SQL_TSI_YEAR.</Error>
      
        <!-- MAINTENANCE NOTE: This translation needs to be reviewed -->
        <!-- [42000]: Second argument invalid for CAST. -->
        <Error Key="InvalidSecondArgForCastFn" NativeErrorCode="31353" _locID="4.InvalidSecondArgForCastFn">Second argument for CAST is not a valid SQL_* type name.</Error>

        <!-- MAINTENANCE NOTE: This translation needs to be reviewed -->
        <!-- [42000]: Invalid type parameter for type in CAST/CONVERT -->
        <Error Key="InvalidTypeParamForCastOrConvert" Params="2" NativeErrorCode="31354" _locID="4.InvalidTypeParamForCastOrConvert">"%1%" is not a valid type parameter for the type passed to %2%.</Error>

        <!-- [42000]: Invalid arithmetic expression operand type. -->
        <Error Key="InvalidArithmeticOperandType" Params="2" NativeErrorCode="31360" _locID="4.InvalidArithmeticOperandType">Type %1% is invalid for the %2% operator.</Error>

        <!-- [42000]: Invalid binary arithmetic expression operand type. -->
        <Error Key="InvalidBinaryArithmeticOperandType" Params="3" NativeErrorCode="31361" _locID="4.InvalidBinaryArithmeticOperandType">Types %1% and %2% are invalid for the %3% operator.</Error>

        <!-- [42000]: Invalid value in value list. -->
        <Error Key="InvalidValueInValueList" NativeErrorCode="31370" Params="0" _locID="4.InvalidValueInValueList">Invalid value in value list.</Error>

        <!-- [42000]: Invalid value for TOP N. -->
        <Error Key="InvalidValueForTopN" Params="1" NativeErrorCode="31371" _locID="4.InvalidValueForTopN">Invalid value for TOP: value must be a positive integer: %1%</Error>

        <!-- [42000]: Invalid value for TOP PERCENT. -->
        <Error Key="InvalidValueForTopPercent" Params="1" NativeErrorCode="31372" _locID="4.InvalidValueForTopPercent">Invalid value for TOP PERCENT: value must be a positive number between 0 and 100: %1%</Error>

        <!-- [HY000]: Can't compute row count for TOP PERCENT. -->
        <Error Key="TopPercentCantComputeRowCount" Params="0" NativeErrorCode="31373" _locID="4.TopPercentCantComputeRowCount">Could not compute row count for TOP PERCENT.</Error>

        <!-- [42000]: Multiple columns from different query scope are found in an aggregate function. -->
        <Error Key="MultiColumnsInAggrFn" Params="0" NativeErrorCode="31380" _locID="4.MultiColumnsInAggrFn">Multiple columns are specified in an aggregated function containing an outer reference. If an aggregate function contains an outer reference, then that outer reference must be the only column reference.</Error>

        <!-- [42000]: Multiple expressions in the select list of a sub-query. -->
        <Error Key="MultiExprsInSubQuery" Params="0" NativeErrorCode="31390" _locID="4.MultiExprsInSubQuery">Multiple expressions found in the select list of a subquery not introduced by EXISTS.</Error>

        <!-- [42000]: Multi-part column could not be bound. -->
        <Error Key="MultiPartColNameNotBound" Params="1" NativeErrorCode="31400" _locID="4.MultiPartColNameNotBound">Qualified column could not be bound: %1%.</Error>

        <!-- [42000]: Nested aggregate function not allowed. -->
        <Error Key="NestedAggrFunctionNotAllowed" NativeErrorCode="31410" _locID="4.NestedAggrFunctionNotAllowed">An aggregate function may not contain an aggregate function or a subquery.</Error>
      
        <!-- [42000]: No column name specified for a column. -->
        <Error Key="NoColumnNameSpecifiedRelationNameUnknown" Params="1" NativeErrorCode="31415" _locID="4.NoColumnNameSpecifiedRelationNameUnknown">Column name not specified for column %1% of table/sub-query.</Error>

        <!-- [42000]: No column name specified for a column. -->
        <Error Key="NoColumnNameSpecified" Params="2" NativeErrorCode="31420" _locID="4.NoColumnNameSpecified">Column name not specified for column %1% of table/sub-query '%2%'.</Error>

        <!-- [42000]: No Merge operation specified (either an insert or update statement required) -->
        <Error Key="NoMergeOperationSpecified" Params="0" NativeErrorCode="31421" _locID="4.NoMergeOperationSpecified">MERGE must specify at least one of WHEN MATCHED or WHEN NOT MATCHED.</Error>
        
        <!-- [42000]: A column is neither in an aggregate function nor from the GROUP BY clause. -->
        <Error Key="NonGroupingColInSelList" Params="1" NativeErrorCode="31430" _locID="4.NonGroupingColInSelList">Column '%1%' is neither in an aggregate function nor from the GROUP BY clause.</Error>

        <!-- [42000]: Non-unique Column Reference. -->
        <Error Key="NonUniqueColRef" Params="1" NativeErrorCode="31440" _locID="4.NonUniqueColRef">Non-unique column reference: %1%.</Error>

        <!-- [42000]: ORDER BY expressions must appear in the select list when SELECT DISTINCT is present. -->
        <Error Key="OrderByExprNotInSelectDistinct" NativeErrorCode="31450" _locID="4.OrderByExprNotInSelectDistinct">ORDER BY expressions must appear in the select list when SELECT DISTINCT is present.</Error>

        <!-- [42000]: ORDER BY expressions must appear in the select list when EXCEPT, INTERSECT or UNION is present. -->
        <Error Key="OrderByExprNotInSelectList" NativeErrorCode="31460" _locID="4.OrderByExprNotInSelectList">ORDER BY expressions must appear in the select list of the first query specification when EXCEPT, INTERSECT or UNION is present.</Error>

        <!-- [42000]: ORDER BY position number out of range.-->
        <Error Key="OrderByPositionNumberOutOfRange" NativeErrorCode="31470" _locID="4.OrderByPositionNumberOutOfRange">Out of range position number in ORDER BY.</Error>

        <!-- [42000]: GROUP BY position number out of range.-->
        <Error Key="GroupByPositionNumberOutOfRange" NativeErrorCode="31473" _locID="4.GroupByPositionNumberOutOfRange">Out of range position number in GROUP BY.</Error>

        <!-- [42000]: GROUP BY position number out of range.-->
        <Error Key="GroupByPositionNumberWithStar" NativeErrorCode="31474" _locID="4.GroupByPositionNumberWithStar">GROUP BY may not refer to the SELECT list using a column ordinal when the SELECT list contains a '*'.</Error>

        <!-- [42000]: ORDER BY occurs in a subquery without an accompanying TOP.-->
        <Error Key="OrderByInSubQueryWithoutTop" NativeErrorCode="31475" _locID="4.OrderByInSubQueryWithoutTop">ORDER BY may only occur in a subquery when accompanied by TOP or LIMIT.</Error>

        <!-- [42000]: Parsing failure. -->
        <Error Key="ParsingFailure" Params="2" NativeErrorCode="31480" _locID="4.ParsingFailure">%1% near '%2%'.</Error>

        <!-- [42000]: Unknown parsing failure. -->
        <Error Key="UknownParsingFailure" Params="0" NativeErrorCode="31490" _locID="4.UknownParsingFailure">Unknown parsing failure.</Error>

        <!-- [42000]: Row value constructor not supported in predicates. -->
        <Error Key="RowConstructorNotSupported" NativeErrorCode="31500" _locID="4.RowConstructorNotSupported">Row value constructor not supported in predicates such as quantified comparisons, IN, BETWEEN.</Error>

        <!-- [42000]: Table or correlation name not unique. -->
        <Error Key="TableOrCorNameNotUnique" Params="1" NativeErrorCode="31510" _locID="4.TableOrCorNameNotUnique">Table/correlation name not unique: %1%.</Error>

        <!-- [42000]: Set functions are found in an IF condition. -->
        <Error Key="SetFnInIFCond" Params="0" NativeErrorCode="31520" _locID="4.SetFnInIFCond">Set functions are not allowed in IF conditions.</Error>

        <!-- [42000]: Sub-queries are found in an IF condition. -->
        <Error Key="SubQueryInIFCond" Params="0" NativeErrorCode="31530" _locID="4.SubQueryInIFCond">Sub-queries are not allowed in IF conditions.</Error>
      
        <!-- [42000]: The length of the given binary literal exceeds the maximum. -->
        <Error Key="MaxBinaryLiteralLenExceeded" Params="2" NativeErrorCode="31540" _locID="4.MaxBinaryLiteralLenExceeded">Binary literal '%1%' is longer than the maximum: %2%.</Error>
      
        <!-- [42000]: The length of the given character literal exceeds the maximum. -->
        <Error Key="MaxCharLiteralLenExceeded" Params="2" NativeErrorCode="31550" _locID="4.MaxCharLiteralLenExceeded">Character literal '%1%' is longer than the maximum: %2%.</Error>
      
        <!-- [42000]: The size of the index exceeds the maximum. -->