<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Messages[<!ELEMENT Messages (Package*)>

<!ELEMENT Package (Error*)>
<!ATTLIST Package ID CDATA #REQUIRED>
<!ATTLIST Package DefaultComponent CDATA #REQUIRED>

<!ELEMENT Error (#PCDATA)>
<!ATTLIST Error Key CDATA #REQUIRED>
<!ATTLIST Error _locID CDATA "0">
<!ATTLIST Error Component CDATA #IMPLIED>
<!ATTLIST Error NativeErrorCode CDATA #REQUIRED>
<!ATTLIST Error Params CDATA "0">]>

<Messages>
    <!-- Package DS_ERROR. ID corresponds to the DS_ERROR constant defined in DriverSupport.h -->
    <Package ID="110" DefaultComponent="DriverSupport">
        <!-- Error thrown when an error occurs while trying to load a string resource for the dialog. -->
        <Error Key="DSStringResourceError" Params="1" NativeErrorCode="1000" _locID="110.DSStringResourceError">String resource %1% not found.</Error>

        <!-- Error thrown when an error occurs while trying to load a cursor resource.. -->
        <Error Key="DSCursorResourceError" Params="1" NativeErrorCode="1010" _locID="110.DSCursorResourceError">An error occurred while attempting to load a cursor: %1%</Error>

        <!-- Error thrown when an error occurs while trying to encrypt data. -->
        <Error Key="DSEncryptError" Params="1" NativeErrorCode="1020" _locID="110.DSEncryptError">An error occurred while attempting to encrypt data: %1%</Error>
      
        <!-- Error thrown when an error occurs while trying to decrypt data. -->
        <Error Key="DSDecryptError" Params="1" NativeErrorCode="1030" _locID="110.DSDecryptError">Failed to decrypt data: %1%</Error>
      
        <!-- Error thrown when an error occurs while trying to initialize SSL context. -->
         <Error Key="DSSSLError" Params="1" NativeErrorCode="1040" _locID="110.DSSSLError">Failed to initialize SSL context: %1%</Error>
     
        <!-- Error thrown when OpenSSL was unable to allocate enough memory. -->
        <Error Key="DSOpenSSLOutofMemory" Params="1" NativeErrorCode="1041" _locID="110.DSOpenSSLOutofMemory">An error occurred while allocating memory to create: %1%</Error>

        <!-- Error thrown when an error occurs while converting server SSL certificate into CryptoAPI format. -->
        <Error Key="DSSSLServerCertConvertError" Params="0" NativeErrorCode="1050" _locID="110.DSSSLServerCertConvertError">Failed to convert certificate from OpenSSL to CryptoAPI.</Error>

        <!-- Error thrown when an the driver has been locked by a vendor. -->
        <Error Key="DSDriverLockedError" Params="1" NativeErrorCode="1060" _locID="110.DSDriverLockedError">Driver has been locked by the vendor %1% and is not licensed for use with this application.</Error>

        <!-- Error thrown when an the driver has been locked by a vendor. -->
        <Error Key="DSDIDFileMissingError" Params="1" NativeErrorCode="1070" _locID="110.DSDIDFileMissingError">Cannot access file %1%. The driver cannot function properly without the file.</Error>

        <!-- Error thrown when OpenSSL functions return an error. -->
        <Error Key="DSOpenSSLError" Params="2" NativeErrorCode="1080" _locID="110.DSOpenSSLError">OpenSSL function %1% returned error: %2%</Error>

        <!-- Error thrown when CSV parser encounters an error. -->
        <Error Key="CSVParser" Params="1" NativeErrorCode="1090" _locID="110.CSVParser">Error parsing CSV. [%1%]</Error>

        <!-- Error thrown when SSL verification fails because trust store does not have right CA certs to verify the server certificate. -->
        <Error Key="DSSslNoCaError" Params="0" NativeErrorCode="1100" _locID="110.DSSslNoCaError">SSL certificate verification failed because the certificate is missing or incorrect.</Error>

        <!-- Error thrown when cURL is not able to receive the expected response from the server due to either incorrect host/port specified or SSL not enabled for connection when connecting to SSL enabled server. -->
        <Error Key="DSCurlRecvError" Params="0" NativeErrorCode="1110" _locID="110.DSCurlRecvError">Unexpected response received from server. Please ensure the server host and port specified for the connection are correct and confirm if SSL should be enabled for the connection.</Error>

        <!-- Error thrown when server host name does not match server SSL certificate subject common name (CN) or any of the "DNS Name" entries in the "Subject Alternative Name". -->
        <Error Key="DSServerHostAndCnSubjectMismatch" Params="0" NativeErrorCode="1120" _locID="110.DSServerHostAndCnSubjectMismatch">SSL verification failed because the server host name specified for the connection does not match the "CN" entry in the "Subject" field or any of the "DNS Name" entries of the "Subject Alternative Name" field in the server certificate.</Error>

        <!-- Error thrown when enabling SSL for the connection when connecting to a server that has not enabled SSL.-->
        <Error Key="DSSslConnectionToNonSslServerError" Params="0" NativeErrorCode="1130" _locID="110.DSSslConnectionToNonSslServerError">Cannot enable SSL for the connection when connecting to a server that has not enabled SSL.</Error>

        <!-- Error thrown when CA certificates can not be read from the CA certificates file. -->
        <Error Key="DSCaCertsFileLoadError" Params="0" NativeErrorCode="1140" _locID="110.DSCaCertsFileLoadError">Unable to load CA certificates from certs file location.  Please ensure the file exists, has read permission, and has the correct PEM format.</Error>

        <!-- Error thrown when enabling SSL for the connection when connecting to a server that has not enabled SSL or if server has been configured to use SSLv2 or SSLv3 but they are not allowed by the driver.-->
        <Error Key="DSSslConnectErrorSsl2AndSsl3NotAllowed" Params="0" NativeErrorCode="1150" _locID="110.DSSslConnectErrorSsl2AndSsl3NotAllowed">Cannot enable SSL for the connection when connecting to a server that has not enabled SSL. If the server has SSL enabled, please check if it has been configured to use SSLv2 or SSLv3 protocols. SSLv2 and SSLv3 protocols are not allowed by the driver as they are insecure.</Error>

        <!-- Error thrown when enabling SSL for the connection when connecting to a server that has not enabled SSL or if server has been configured to use SSL protocol version lower than what is allowed by the connection.-->
        <Error Key="DSSslConnectErrorLowerThanMinTls" Params="1" NativeErrorCode="1160" _locID="110.DSSslConnectErrorLowerThanMinTls">Cannot enable SSL for the connection when connecting to a server that has not enabled SSL. If the server has SSL enabled, please check if it has been configured to use a SSL protocol version that is lower than what is allowed for the connection. The minimum SSL protocol version allowed for the connection is: %1%.</Error>

        <!-- Error thrown when driver is not able to receive the expected response from the server due to incorrect host/port specified. -->
        <Error Key="DSWrongServerError" Params="0" NativeErrorCode="1170" _locID="110.DSWrongServerError">Unexpected response received from server. Please ensure the server host and port specified for the connection are correct.</Error>

        <!-- Error thrown when driver is not able to receive an invalid port valid. -->
        <Error Key="DSInvalidPortError" Params="1" NativeErrorCode="1180" _locID="110.DSInvalidPortError">Incorrect %1% specified. Please check your configuration.</Error>

        <!-- Error thrown when the client private key properties are not provided while two-way SSL feature is enabled. -->
        <Error Key="DSClientPrivateKeyPropsNeededError" Params="0" NativeErrorCode="1190" _locID="110.DSClientPrivateKeyPropsNeededError">The client private key properties are not provided while two-way SSL feature is enabled.</Error>

        <!-- X509 or Windows Truststore error thrown when ssl handshake failed.-->
        <Error Key="DSSslErrorMessage " Params="1" NativeErrorCode="1200" _locID="110.DSSslErrorMessage ">%1%</Error>
		
        <!-- Error thrown when Client certificate or Client key can not be read from the Client certificate or Client private key file. -->
        <Error Key="DSClientCertOrKeyFileLoadError" Params="0" NativeErrorCode="1210" _locID="110.DSClientCertOrKeyFileLoadError">Unable to load Client certificate or Client private key set via the connection attributes ClientCert or ClientPrivateKey. Please ensure the file exists, has read permission, and has the correct PEM format.</Error>

      <!--Rapidjson Error Messages-->
        <!-- Errors from rapidjson, rapidjson enum value is NativeErrorCode minus 2000. Messages from error.h in rapidjson library. -->
        <Error Key="DSkParseErrorNone" Params="0" NativeErrorCode="2000" _locID="110.DSkParseErrorNone">JSON parsing error: No error.</Error>
        <Error Key="DSkParseErrorDocumentEmpty" Params="0" NativeErrorCode="2001" _locID="110.DSkParseErrorDocumentEmpty">JSON parsing error: The document is empty.</Error>
        <Error Key="DSkParseErrorDocumentRootNotSingular" Params="0" NativeErrorCode="2002" _locID="110.DSkParseErrorDocumentRootNotSingular">JSON parsing error: The document root must not follow by other values.</Error>
        <Error Key="DSkParseErrorValueInvalid" Params="0" NativeErrorCode="2003" _locID="110.DSkParseErrorValueInvalid">JSON parsing error: Invalid value.</Error>
        <Error Key="DSkParseErrorObjectMissName" Params="0" NativeErrorCode="2004" _locID="110.DSkParseErrorObjectMissName">JSON parsing error: Missing a name for object member.</Error>
        <Error Key="DSkParseErrorObjectMissColon" Params="0" NativeErrorCode="2005" _locID="110.DSkParseErrorObjectMissColon">JSON parsing error: Missing a colon after a name of object member.</Error>
        <Error Key="DSkParseErrorObjectMissCommaOrCurlyBracket" Params="0" NativeErrorCode="2006" _locID="110.DSkParseErrorObjectMissCommaOrCurlyBracket">JSON parsing error: Missing a comma or '}' after an object member.</Error>
        <Error Key="DSkParseErrorArrayMissCommaOrSquareBracket" Params="0" NativeErrorCode="2007" _locID="110.DSkParseErrorArrayMissCommaOrSquareBracket">JSON parsing error: Missing a comma or ']' after an array element.</Error>
        <Error Key="DSkParseErrorStringUnicodeEscapeInvalidHex" Params="0" NativeErrorCode="2008" _locID="110.DSkParseErrorStringUnicodeEscapeInvalidHex">JSON parsing error: Incorrect hex digit after \\u escape in string.</Error>
        <Error Key="DSkParseErrorStringUnicodeSurrogateInvalid" Params="0" NativeErrorCode="2009" _locID="110.DSkParseErrorStringUnicodeSurrogateInvalid">JSON parsing error: The surrogate pair in string is invalid.</Error>
        <Error Key="DSkParseErrorStringEscapeInvalid" Params="0" NativeErrorCode="2010" _locID="110.DSkParseErrorStringEscapeInvalid">JSON parsing error: Invalid escape character in string.</Error>
        <Error Key="DSkParseErrorStringMissQuotationMark" Params="0" NativeErrorCode="2011" _locID="110.DSkParseErrorStringMissQuotationMark">JSON parsing error: Missing a closing quotation mark in string.</Error>
        <Error Key="DSkParseErrorStringInvalidEncoding" Params="0" NativeErrorCode="2012" _locID="110.DSkParseErrorStringInvalidEncoding">JSON parsing error: Invalid encoding in string.</Error>
        <Error Key="DSkParseErrorNumberTooBig" Params="0" NativeErrorCode="2013" _locID="110.DSkParseErrorNumberTooBig">JSON parsing error: Number too big to be stored in double.</Error>
        <Error Key="DSkParseErrorNumberMissFraction" Params="0" NativeErrorCode="2014" _locID="110.DSkParseErrorNumberMissFraction">JSON parsing error: Miss fraction part in number.</Error>
        <Error Key="DSkParseErrorNumberMissExponent" Params="0" NativeErrorCode="2015" _locID="110.DSkParseErrorNumberMissExponent">JSON parsing error: Miss exponent in number.</Error>
        <Error Key="DSkParseErrorTermination" Params="0" NativeErrorCode="2016" _locID="110.DSkParseErrorTermination">JSON parsing error: Parsing was terminated.</Error>
        <Error Key="DSkParseErrorUnspecificSyntaxError" Params="0" NativeErrorCode="2017" _locID="110.DSkParseErrorUnspecificSyntaxError">JSON parsing error: Unspecific syntax error.</Error>

      <!-- Error thrown when the column doesn't exisit. -->
      <Error Key="InvalidColumnNum" Params="1" NativeErrorCode="2018" _locID="110.InvalidColumnNum">%1% doesn't exisit; BadColumnException.</Error>
      
      <!-- Error thrown when the user agent entry is invalid. -->
      <Error Key="InvalidUserAgentEntry" Params="0" NativeErrorCode="2019" _locID="110.InvalidUserAgentEntry">Invalid user agent entry.</Error>
    
      <!-- Error thrown when the user agent comment is not enclosed in parentheses. -->
      <Error Key="UserAgentCommentNotEnclosedInParen" Params="0" NativeErrorCode="2020" _locID="110.UserAgentCommentNotEnclosedInParen">Invalid user-agent string. The entire comment must be enclosed in parentheses.</Error>

      <!-- Error thrown when the user agent comment contains an invalid character. -->
      <Error Key="InvalidCharacterInUserAgentComment" Params="1" NativeErrorCode="2021" _locID="110.InvalidCharacterInUserAgentComment">Invalid character '%1%' found in user-agent comment.</Error>

      <!-- Error thrown when the user agent product contains an invalid character. -->
      <Error Key="InvalidCharacterInUserAgentProductName" Params="1" NativeErrorCode="2022" _locID="110.InvalidCharacterInUserAgentProductName">Invalid character '%1%' found in user-agent product name.</Error>

      <!-- Error thrown when the user agent product version contains an invalid character. -->
      <Error Key="InvalidCharacterInUserAgentProductVer" Params="1" NativeErrorCode="2023" _locID="110.InvalidCharacterInUserAgentProductVer">Invalid character '%1%' found in user-agent product version.</Error>

      <!-- Error thrown when an empty product name is specific in the user-agent entry. -->
      <Error Key="UserAgentEmptyProductName" Params="0" NativeErrorCode="2024" _locID="110.UserAgentEmptyProductName">Empty product name is not allowed in the user-agent entry.</Error>

      <!-- Error thrown when an empty product version is specific in the user-agent entry. -->
      <Error Key="UserAgentEmptyProductVer" Params="0" NativeErrorCode="2025" _locID="110.UserAgentEmptyProductVer">Empty product version is not allowed in the user-agent entry.</Error>
    </Package>
</Messages>
